# Generated by Django 5.0.6 on 2024-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_group_date_message_date_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="members_online",
            field=models.IntegerField(default=0),
        ),
    ]
